export enum SERVER_CATEGORY {
  SURVIVAL = "Survival",
  PVP = "PvP",
  ECONOMY = "Economy",
  VANILLA = "Vanilla",
  PVE = "PvE",
  LIFESTEAL = "Lifesteal",
  TOWNY = "Towny",
  SKYBLOCK = "Skyblock",
  MINIGAMES = "Minigames",
  RPG = "RPG",
  FACTIONS = "Factions",
  PRISON = "Prison",
  PARKOUR = "Parkour",
  ANARCHY = "Anarchy",
  PLOTS = "Plots",
  ADVENTURE = "Adventure",
  MODDED = "Modded",
}
